export const HTTP_RESPONSE_OK = 200;
export const HTTP_RESPONSE_BAD_REQUEST = 400;
export const HTTP_RESPONSE_UNAUTHORIZED = 401;
export const HTTP_RESPONSE_NOT_FOUND = 404;
export const HTTP_RESPONSE_METHOD_NOT_ALLOWED = 405;
export const HTTP_RESPONSE_INTERNAL_SERVER_ERROR = 500;